"""Removed longitude and latitude columns and added category and priority

Revision ID: ebefccd5debb
Revises: 57dcababc764
Create Date: 2025-07-10 05:03:52.097989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ebefccd5debb'
down_revision = '57dcababc764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('pending', 'resolved', 'rejected', name='report_status'), nullable=False))
        batch_op.add_column(sa.Column('priority', sa.Enum('low', 'medium', 'high', name='report_priority'), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=128), nullable=True))
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('latitude', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('location')
        batch_op.drop_column('priority')
        batch_op.drop_column('status')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
